import Foundation

enum AppStoryboard: String {
    case signIn = "SignIn"
    case drawer = "Drawer"
    case dashboard = "Dashboard"
    case onBoarding = "OnBoarding"
    case settings = "Settings"
    case taskDetail = "TaskDetail"
    case registration = "Registration"
    case home = "Home"
    case profile = "Profile"
    case searchHackathons = "SearchHackathons"
    case teamList = "TeamList"
    case createTeam = "CreateTeam"
    case hackathonDetail = "HackathonDetail"
    case chatList = "ChatList"
    case chooseSearchCategory = "ChooseSearchCategory"
    case hackathonList = "HackathonList"
    case teamSearch = "TeamSearch"
    case teammateSearch = "TeammateSearch"
    case hackFilterDialog = "HackFilterDialog"
    case editProfile = "EditProfile"
    case hackMemberList = "HackMemberList"
    case hackTeamList = "HackTeamList"
    case hackTeamDetails = "HackTeamDetails"
    case startUpScreen = "StartUpScreen"
    case userDetails = "UserDetails"
    case chat = "Chat"
    case userRequests = "UserRequests"
    case selectTeam = "SelectTeam"
    case sentRequest = "SentRequest"
    case bookmarkedUsers = "BookmarkedUsers"
    case bookmarkedTeams = "BookmarkedTeams"
    case bookmarkedHacks = "BookmarkedHacks"
    case bookmarks = "Bookmarks"
    case selectTags = "SelectTags"
}
